llm:
  api_key: "AIzaSyC9prhgpFUhbDFCI6PbRTFjBYFioFwj2Yc"   # API key for your LLM provider (e.g. OpenAI)
  model: "gemini/gemini-2.0-flash"         # Model identifier to use
  api_var: "GEMINI_API_KEY"

read_folder: "./resources"     # Folder where files are read from
write_folder: "./write"   # Folder where files are written to
